version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: pgdb
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: employee-management-system
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pgdb -d employee-management-system" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    command: >
      sh -c "sleep 10 &&
      npx typeorm migration:run -d /app/dist/data-source.js &&
      node dist/main.js"  # Start the application directly
    env_file:
      - .env

volumes:
  postgres-data:

networks:
  app-network: